trigger:
  branches:
    include:
      - main

variables:
  dockerRegistryServiceConnection: 'dockerhub'
  dockerUsername: 'chudat753'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndPush
  strategy:
    matrix:
      sales-order-system:
        folder: '/sales-order-system'
        imageName: 'sales-order-system'
      user-service:
        folder: 'user-service'
        imageName: 'user-service'
      customer-service:
        folder: 'customer-service'
        imageName: 'customer-service'
      order-service:
        folder: 'order-service'
        imageName: 'order-service'
      product-service:
        folder: 'product-service'
        imageName: 'product-service'
  steps:
  - checkout: self

  - task: Docker@2
    displayName: Docker Login
    inputs:
      command: login
      containerRegistry: $(dockerRegistryServiceConnection)

  - task: Docker@2
    displayName: Build Docker Image
    inputs:
      command: build
      repository: docker.io/$(dockerUsername)/$(imageName)
      dockerfile: $(folder)/Dockerfile
      tags: |
        $(Build.BuildId)

  - task: Docker@2
    displayName: Push Docker Image
    inputs:
      command: push
      repository: docker.io/$(dockerUsername)/$(imageName)
      tags: |
        $(Build.BuildId)
