name: CI/CD – Microservice Build

on:
  push:
    branches: [ main ]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.set.outputs.changed }}
    steps:
      - uses: actions/checkout@v4

      - id: set
        run: |
          CHANGED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | cut -d/ -f1 | sort -u | uniq | grep '^service-')
          echo "Changed services: $CHANGED"
          echo "changed=${CHANGED}" >> $GITHUB_OUTPUT

  build:
    needs: detect-changes
    runs-on: ubuntu-latest
    if: needs.detect-changes.outputs.changed != ''
    strategy:
      matrix:
        service: ${{ fromJson(needs.detect-changes.outputs.changed) }}
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push
        run: |
          docker build -t docker.io/chudat753/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push docker.io/chudat753/${{ matrix.service }}:latest
