# .github/workflows/ci-cd.yml
name: CI/CD for All Microservices

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service, customer-service, order-service, product-service] # add more as needed
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push image
        run: |
          docker build -t docker.io/youruser/${{ matrix.service }}:latest ./${{ matrix.service }}
          docker push docker.io/youruser/${{ matrix.service }}:latest
