name: trigger CI

on:
  push:
    branches: [main]

jobs:
  trigger-openshift:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Openshift
        run: |
          curl -X POST http://el-multi-service-ci-listener-chuanhdat-dev.apps.rm2.thpm.p1.openshiftapps.com \
            -H "Content-Type: application/json" \
            -d '{
              "template_name": "multi-service-ci-template",
              "repo-url": "https://github.com/DatCD85/test-app.git",
              "revision": "main",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "services": ["sales-order-system", "user-service", "customer-service", "order-service", "product-service"],
              "cd-trigger-url": "http://el-github-listener-chuanhdat-dev.apps.rm2.thpm.p1.openshiftapps.com"
            }'

