name: trigger CD
on:
  workflow_run:
    workflows: ["CI/CD for All Microservices"]
    types:
      - completed

jobs:
  trigger-openshift:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Openshift
        run: |
         curl -X POST http://el-github-listener-chuanhdat-dev.apps.rm2.thpm.p1.openshiftapps.com \
         -H "Content-Type: application/json" \
         -d '{
             "template_name": "sales-order-system-template",
             "image": "docker.io/chudat753/maven-app:latest",
             "commit": "${{ github.event.workflow_run.head_commit.id }}",
             "branch": "${{ github.event.workflow_run.head_branch }}"
         }'
