name: trigger CD
on:
  workflow_run:
    workflows: ["Maven CI"]
    types:
      - completed

jobs:
  trigger-openshift:
    runs-on: ubuntu-latest
    steps:
      - name: Send webhook to Openshift
        run: |
          curl -X POST https://webhook.site/e9b7cc44-488d-4ff6-9195-02b18abdffb6
            -H "Content-Type: application/json" \
            -d '{
            "template_name": "maven-app-template",
            "image": "docker.io/chudat753/maven-app:latest"
              }'
#            "commit": "${{ github.event.workflow_run.head_commit.id }}",
#            "branch": "${{ github.event.workflow_run.head_branch }}"
